-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 19:27:55 2021
-- Model: BURGUER BOSS   Version: 1.0
-- MySQL Workbench Forward Engineering
-- drop database burguerboss;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema burguerboss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema burguerboss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `burguerboss` DEFAULT CHARACTER SET utf8 ;
USE `burguerboss` ;

CREATE TABLE IF NOT EXISTS `burguerboss`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `burguerboss`.`lanches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burguerboss`.`lanches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `pathLanche` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`idcategoria`)
    REFERENCES `burguerboss`.`categorias` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burguerboss`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burguerboss`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL UNIQUE,
  `senha` VARCHAR(256) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burguerboss`.`comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burguerboss`.`comandas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valorTotal` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burguerboss`.`carrinhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `burguerboss`.`carrinhos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idlanche` INT NOT NULL,
  `idcomanda` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idlanche`)
    REFERENCES `burguerboss`.`lanches` (`id`),
    FOREIGN KEY (`idcomanda`)
    REFERENCES `burguerboss`.`comandas` (`id`)
);

insert into categorias (nome, tipo) values('Hamburguer','comida');
insert into categorias (nome, tipo) values('Refrigerante','bebida');
insert into categorias (nome, tipo) values('Batata','comida');
insert into categorias (nome, tipo) values('Combo','comida');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

