-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 19:27:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`lanches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lanches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imgcomida` BINARY NOT NULL,
  `valor` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 'time',
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL DEFAULT 'UNIQUE',
  `senha` VARCHAR(256) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comandas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valorTotal` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinhos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `idlanche` INT NOT NULL,
  `idcomanda` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrinhos_lanches_idx` (`idlanche` ASC) VISIBLE,
  INDEX `fk_carrinhos_comandas1_idx` (`idcomanda` ASC) VISIBLE,
  CONSTRAINT `fk_carrinhos_lanches`
    FOREIGN KEY (`idlanche`)
    REFERENCES `mydb`.`lanches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinhos_comandas1`
    FOREIGN KEY (`idcomanda`)
    REFERENCES `mydb`.`comandas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
